# Generated by Django 2.0.9 on 2020-05-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_item_saving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Serial numbers'},
        ),
    ]
